### ISSUE TITLE
mvn test - sql

### ISSUE THREAD

**Issue by Yikun** [Yikun/spark-arm-docker#32]
SPARK-34399: Add job commit duration metrics for DataWritingCommand *** FAILED ***
build/sbt "sql/testOnly *SQLMetricsSuite -- -z SPARK-34399"

Check source for different kind of UDFs *** FAILED ***

SPARK-36381: Check column name exist case sensitive and insensitive when add column *** FAILED ***
SPARK-36381: Check column name exist case sensitive and insensitive when rename column *** FAILED ***

**Comment by Yikun** [comment]
```
[info] HiveExternalCatalogVersionsSuite:
2021-08-08 15:05:59.382 - stderr> 21/08/08 22:05:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-08-08 15:05:59.625 - stderr> Exception in thread "main" java.io.IOException: Cannot run program "python": error=2, No such file or directory
2021-08-08 15:05:59.625 - stderr> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:97)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
2021-08-08 15:05:59.625 - stderr> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-08 15:05:59.625 - stderr> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-08-08 15:05:59.625 - stderr> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-08 15:05:59.625 - stderr> 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
2021-08-08 15:05:59.625 - stderr> 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
2021-08-08 15:05:59.626 - stderr> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
2021-08-08 15:05:59.626 - stderr> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2021-08-08 15:05:59.626 - stderr> Caused by: java.io.IOException: error=2, No such file or directory
2021-08-08 15:05:59.626 - stderr> 	at java.lang.UNIXProcess.forkAndExec(Native Method)
2021-08-08 15:05:59.626 - stderr> 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
2021-08-08 15:05:59.626 - stderr> 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
2021-08-08 15:05:59.626 - stderr> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2021-08-08 15:05:59.626 - stderr> 	... 14 more
2021-08-08 15:05:59.63 - stderr> log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
2021-08-08 15:05:59.63 - stderr> log4j:WARN Please initialize the log4j system properly.
2021-08-08 15:05:59.63 - stderr> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by Yikun** [comment]
```
ERROR [0.804s]: test_mad (pyspark.pandas.tests.test_series.SeriesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/spark/spark-master-test-maven-arm/python/pyspark/pandas/tests/test_series.py", line 2128, in test_mad
    self.assert_eq(pser.mad(), psser.mad())
  File "/home/spark/spark-master-test-maven-arm/python/pyspark/testing/pandasutils.py", line 234, in assert_eq
    self.assertEqual(lobj, robj)
AssertionError: 21.555555555555554 != 21.555555555555557

----------------------------------------------------------------------
```
